-- Systeme de codes surprise marketing (QR/link + saisie manuelle PC)
-- Appliquer ce script dans Supabase SQL Editor.

alter table if exists public.badges_catalog_reborn
  add column if not exists is_shop_visible boolean not null default true;

create table if not exists public.surprise_codes_reborn (
  id uuid primary key default gen_random_uuid(),
  code text not null,
  label text,
  description text,
  bonus_money integer not null default 0,
  bonus_badge_id uuid references public.badges_catalog_reborn(id) on delete set null,
  bonus_badge_ids uuid[] not null default '{}',
  valid_from timestamptz not null default now(),
  valid_until timestamptz,
  is_enabled boolean not null default true,
  single_global_use boolean not null default false,
  max_total_uses integer,
  limit_per_account boolean not null default true,
  limit_per_device boolean not null default true,
  limit_per_ip boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint surprise_codes_reborn_code_not_blank check (length(trim(code)) >= 3),
  constraint surprise_codes_reborn_bonus_not_empty check (
    bonus_money > 0
    or bonus_badge_id is not null
    or coalesce(array_length(bonus_badge_ids, 1), 0) > 0
  ),
  constraint surprise_codes_reborn_dates_valid check (valid_until is null or valid_until >= valid_from),
  constraint surprise_codes_reborn_max_uses_valid check (max_total_uses is null or max_total_uses > 0),
  constraint surprise_codes_reborn_single_global_rule check (
    not single_global_use or max_total_uses is null or max_total_uses = 1
  )
);

create unique index if not exists surprise_codes_reborn_code_ci_uidx
  on public.surprise_codes_reborn (upper(trim(code)));

create table if not exists public.surprise_code_redemptions_reborn (
  id bigint generated by default as identity primary key,
  code_id uuid not null references public.surprise_codes_reborn(id) on delete cascade,
  code_snapshot text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  device_id text,
  ip_address inet,
  source text,
  awarded_money integer not null default 0,
  awarded_badge_id uuid references public.badges_catalog_reborn(id) on delete set null,
  awarded_badge_ids uuid[] not null default '{}',
  created_at timestamptz not null default now(),
  constraint surprise_code_redemptions_reborn_awarded_valid check (awarded_money >= 0)
);

alter table if exists public.surprise_codes_reborn
  add column if not exists bonus_badge_ids uuid[] not null default '{}';

alter table if exists public.surprise_codes_reborn
  add column if not exists description text;

alter table if exists public.surprise_code_redemptions_reborn
  add column if not exists awarded_badge_ids uuid[] not null default '{}';

create unique index if not exists surprise_code_redemptions_reborn_user_uidx
  on public.surprise_code_redemptions_reborn (code_id, user_id);

create index if not exists surprise_code_redemptions_reborn_code_idx
  on public.surprise_code_redemptions_reborn (code_id, created_at desc);

create index if not exists surprise_code_redemptions_reborn_device_idx
  on public.surprise_code_redemptions_reborn (code_id, device_id)
  where device_id is not null;

create index if not exists surprise_code_redemptions_reborn_ip_idx
  on public.surprise_code_redemptions_reborn (code_id, ip_address)
  where ip_address is not null;

alter table public.surprise_codes_reborn enable row level security;
alter table public.surprise_code_redemptions_reborn enable row level security;

drop policy if exists surprise_codes_reborn_admin_select on public.surprise_codes_reborn;
create policy surprise_codes_reborn_admin_select
on public.surprise_codes_reborn
for select
to authenticated
using (
  exists (
    select 1
    from public.users_profiles up
    where up.id = auth.uid()
      and (
        upper(coalesce(up.role, '')) like '%ADMIN%'
        or upper(coalesce(up.role_ingame, '')) like '%ADMIN%'
      )
  )
);

drop policy if exists surprise_codes_reborn_admin_insert on public.surprise_codes_reborn;
create policy surprise_codes_reborn_admin_insert
on public.surprise_codes_reborn
for insert
to authenticated
with check (
  exists (
    select 1
    from public.users_profiles up
    where up.id = auth.uid()
      and (
        upper(coalesce(up.role, '')) like '%ADMIN%'
        or upper(coalesce(up.role_ingame, '')) like '%ADMIN%'
      )
  )
);

drop policy if exists surprise_codes_reborn_admin_update on public.surprise_codes_reborn;
create policy surprise_codes_reborn_admin_update
on public.surprise_codes_reborn
for update
to authenticated
using (
  exists (
    select 1
    from public.users_profiles up
    where up.id = auth.uid()
      and (
        upper(coalesce(up.role, '')) like '%ADMIN%'
        or upper(coalesce(up.role_ingame, '')) like '%ADMIN%'
      )
  )
)
with check (
  exists (
    select 1
    from public.users_profiles up
    where up.id = auth.uid()
      and (
        upper(coalesce(up.role, '')) like '%ADMIN%'
        or upper(coalesce(up.role_ingame, '')) like '%ADMIN%'
      )
  )
);

drop policy if exists surprise_codes_reborn_admin_delete on public.surprise_codes_reborn;
create policy surprise_codes_reborn_admin_delete
on public.surprise_codes_reborn
for delete
to authenticated
using (
  exists (
    select 1
    from public.users_profiles up
    where up.id = auth.uid()
      and (
        upper(coalesce(up.role, '')) like '%ADMIN%'
        or upper(coalesce(up.role_ingame, '')) like '%ADMIN%'
      )
  )
);

drop policy if exists surprise_code_redemptions_reborn_admin_select on public.surprise_code_redemptions_reborn;
create policy surprise_code_redemptions_reborn_admin_select
on public.surprise_code_redemptions_reborn
for select
to authenticated
using (
  exists (
    select 1
    from public.users_profiles up
    where up.id = auth.uid()
      and (
        upper(coalesce(up.role, '')) like '%ADMIN%'
        or upper(coalesce(up.role_ingame, '')) like '%ADMIN%'
      )
  )
);

create or replace function public.redeem_surprise_code_reborn(
  p_code text,
  p_device_id text default null,
  p_source text default null
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_code public.surprise_codes_reborn%rowtype;
  v_profile public.users_profiles%rowtype;
  v_now timestamptz := now();
  v_clean_code text := upper(trim(coalesce(p_code, '')));
  v_clean_device_id text := nullif(trim(coalesce(p_device_id, '')), '');
  v_headers_text text := current_setting('request.headers', true);
  v_headers jsonb := '{}'::jsonb;
  v_ip_raw text := null;
  v_ip inet := null;
  v_total_uses integer := 0;
  v_awarded_money integer := 0;
  v_awarded_badge uuid := null;
  v_awarded_badges uuid[] := '{}';
  v_code_badges uuid[] := '{}';
  v_candidate_badge uuid;
begin
  if v_user_id is null then
    return json_build_object('success', false, 'reason', 'NOT_AUTHENTICATED');
  end if;

  if v_clean_code = '' then
    return json_build_object('success', false, 'reason', 'EMPTY_CODE');
  end if;

  select *
  into v_code
  from public.surprise_codes_reborn
  where upper(trim(code)) = v_clean_code
    and is_enabled = true
  for update;

  if not found then
    return json_build_object('success', false, 'reason', 'CODE_NOT_FOUND');
  end if;

  if v_code.valid_from > v_now then
    return json_build_object('success', false, 'reason', 'CODE_NOT_STARTED');
  end if;

  if v_code.valid_until is not null and v_code.valid_until < v_now then
    return json_build_object('success', false, 'reason', 'CODE_EXPIRED');
  end if;

  select *
  into v_profile
  from public.users_profiles
  where id = v_user_id
  for update;

  if not found then
    return json_build_object('success', false, 'reason', 'PROFILE_NOT_FOUND');
  end if;

  if v_code.limit_per_account and exists (
    select 1
    from public.surprise_code_redemptions_reborn r
    where r.code_id = v_code.id
      and r.user_id = v_user_id
  ) then
    return json_build_object('success', false, 'reason', 'ALREADY_REDEEMED_ACCOUNT');
  end if;

  if v_code.limit_per_device and v_clean_device_id is not null and exists (
    select 1
    from public.surprise_code_redemptions_reborn r
    where r.code_id = v_code.id
      and r.device_id = v_clean_device_id
  ) then
    return json_build_object('success', false, 'reason', 'ALREADY_REDEEMED_DEVICE');
  end if;

  if v_headers_text is not null and trim(v_headers_text) <> '' then
    begin
      v_headers := v_headers_text::jsonb;
    exception when others then
      v_headers := '{}'::jsonb;
    end;
  end if;

  v_ip_raw := split_part(coalesce(v_headers ->> 'x-forwarded-for', ''), ',', 1);
  if v_ip_raw = '' then
    v_ip_raw := v_headers ->> 'x-real-ip';
  end if;

  begin
    if v_ip_raw is not null and trim(v_ip_raw) <> '' then
      v_ip := trim(v_ip_raw)::inet;
    end if;
  exception when others then
    v_ip := null;
  end;

  if v_code.limit_per_ip and v_ip is not null and exists (
    select 1
    from public.surprise_code_redemptions_reborn r
    where r.code_id = v_code.id
      and r.ip_address = v_ip
  ) then
    return json_build_object('success', false, 'reason', 'ALREADY_REDEEMED_IP');
  end if;

  select count(*)::integer
  into v_total_uses
  from public.surprise_code_redemptions_reborn r
  where r.code_id = v_code.id;

  if v_code.single_global_use and v_total_uses >= 1 then
    return json_build_object('success', false, 'reason', 'CODE_ALREADY_USED');
  end if;

  if v_code.max_total_uses is not null and v_total_uses >= v_code.max_total_uses then
    return json_build_object('success', false, 'reason', 'CODE_EXHAUSTED');
  end if;

  if v_code.bonus_money > 0 then
    v_awarded_money := v_code.bonus_money;
    update public.users_profiles
    set money = coalesce(money, 0) + v_awarded_money,
        updated_at = now()
    where id = v_user_id;
  end if;

  v_code_badges := array_remove(coalesce(v_code.bonus_badge_ids, '{}'), null);
  if v_code.bonus_badge_id is not null and not (v_code.bonus_badge_id = any(v_code_badges)) then
    v_code_badges := array_append(v_code_badges, v_code.bonus_badge_id);
  end if;

  foreach v_candidate_badge in array v_code_badges loop
    if not exists (
      select 1
      from public.badges_inventory_reborn inv
      where inv.user_id = v_user_id
        and inv.badge_id = v_candidate_badge
    ) then
      insert into public.badges_inventory_reborn (
        user_id,
        badge_id,
        purchase_price,
        purchased_at
      ) values (
        v_user_id,
        v_candidate_badge,
        0,
        now()
      );

      v_awarded_badges := array_append(v_awarded_badges, v_candidate_badge);
      if v_awarded_badge is null then
        v_awarded_badge := v_candidate_badge;
      end if;
    end if;
  end loop;

  insert into public.surprise_code_redemptions_reborn (
    code_id,
    code_snapshot,
    user_id,
    device_id,
    ip_address,
    source,
    awarded_money,
    awarded_badge_id,
    awarded_badge_ids
  ) values (
    v_code.id,
    v_code.code,
    v_user_id,
    v_clean_device_id,
    v_ip,
    nullif(trim(coalesce(p_source, '')), ''),
    v_awarded_money,
    v_awarded_badge,
    v_awarded_badges
  );

  update public.surprise_codes_reborn
  set updated_at = now()
  where id = v_code.id;

  return json_build_object(
    'success', true,
    'code', v_code.code,
    'awarded_money', v_awarded_money,
    'awarded_badge_id', v_awarded_badge,
    'awarded_badge_ids', v_awarded_badges,
    'reason', 'REDEEMED'
  );
end;
$$;

grant execute on function public.redeem_surprise_code_reborn(text, text, text) to authenticated;
